language: objective-c
osx_image: xcode61
rvm:
- 2.1.2

branches:
  only:
    - master
    - development

before_install:
- chmod +x ./Scripts/install.sh

install:
- ./Scripts/install.sh

before_script:
- chmod +x ./Scripts/build.sh
- chmod +x ./Scripts/buildChecker.sh

script:
- ./Scripts/build.sh
- ./Scripts/buildChecker.sh

notifications:
  email:
    - acx234@gmail.com
    - bdavi015@ucr.edu
    - jwest009@ucr.edu
    - iarte001@ucr.edu
    - jmcgh001@gmail.com
    - goknighster@gmail.com
