language: objective-c
osx_image: xcode61
rvm:
- 2.1.2

branches:
  only:
    - master

before_script:
- chmod +x ./Scripts/build.sh

before_install:
- chmod +x ./Scripts/install.sh

install: travis_wait nvm ./Scripts/install.sh
script:
- ./Scripts/build.sh
